package edu.neu.csye6200.ui;

import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jdsha
 */
public class AdminView extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form AdminView
     */
    public AdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        enrollStudentBtn = new javax.swing.JButton();
        registerTeacherBtn = new javax.swing.JButton();
        createClassBtn = new javax.swing.JButton();
        viewStudentsBtn = new javax.swing.JButton();
        viewTeachersBtn = new javax.swing.JButton();
        addImmunizationBtn = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Panel");

        enrollStudentBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enrollStudentBtn.setText("Enroll Student");
        enrollStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollStudentBtnActionPerformed(evt);
            }
        });

        registerTeacherBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        registerTeacherBtn.setText("Register Teacher");
        registerTeacherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerTeacherBtnActionPerformed(evt);
            }
        });

        createClassBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createClassBtn.setText("Create a classroom");
        createClassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createClassBtnActionPerformed(evt);
            }
        });

        viewStudentsBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewStudentsBtn.setText("View all students");
        viewStudentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentsBtnActionPerformed(evt);
            }
        });

        viewTeachersBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewTeachersBtn.setText("View all teachers");
        viewTeachersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTeachersBtnActionPerformed(evt);
            }
        });

        addImmunizationBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addImmunizationBtn.setText("Add Immunization Records");
        addImmunizationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImmunizationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enrollStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(registerTeacherBtn)
                                .addGap(6, 6, 6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createClassBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(viewStudentsBtn)
                        .addGap(18, 18, 18)
                        .addComponent(viewTeachersBtn)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addImmunizationBtn)
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrollStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerTeacherBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createClassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewStudentsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewTeachersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addImmunizationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enrollStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollStudentBtnActionPerformed
        // TODO add your handling code here:    	    
    	
    	JFrame registerStudentFrame = new Registration();
    	registerStudentFrame.setVisible(true);
    	dispose();
    	
    }//GEN-LAST:event_enrollStudentBtnActionPerformed

    private void registerTeacherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerTeacherBtnActionPerformed
        // TODO add your handling code here:
    	
    	JFrame registerTeacherFrame = new TeacherRegistrationView();
    	registerTeacherFrame.setVisible(true);
    	dispose();
    	
    }//GEN-LAST:event_registerTeacherBtnActionPerformed

    private void createClassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createClassBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createClassBtnActionPerformed

    private void viewStudentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentsBtnActionPerformed
        // TODO add your handling code here:
    	
    	JFrame viewStudentsFrame = new AllStudentsView();
    	viewStudentsFrame.setVisible(true);
    	dispose();
    	
    }//GEN-LAST:event_viewStudentsBtnActionPerformed

    private void viewTeachersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTeachersBtnActionPerformed
        // TODO add your handling code here:
    	
    	JFrame viewTeachersFrame = new AllTeachersView();
    	viewTeachersFrame.setVisible(true);
    	dispose();
    	
    }//GEN-LAST:event_viewTeachersBtnActionPerformed

    private void addImmunizationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImmunizationBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addImmunizationBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void launch() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enrollStudentBtn;
    private javax.swing.JButton registerTeacherBtn;
    private javax.swing.JButton createClassBtn;
    private javax.swing.JButton viewStudentsBtn;
    private javax.swing.JButton viewTeachersBtn;
    private javax.swing.JButton addImmunizationBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
