package edu.neu.csye6200.ui;

import javax.swing.JDialog;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jdsha
 */
public class AdminView extends javax.swing.JFrame {
	
	/**
     * Creates new form StudentLogin
     */
    public AdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enrollStudentBtn = new javax.swing.JButton();
        registerTeacherBtn = new javax.swing.JButton();
        welcomeLbl = new javax.swing.JLabel();
        adminLbl = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        title1Lbl = new javax.swing.JLabel();
        title2Lbl = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        viewStudentsBtn = new javax.swing.JButton();
        viewTeachersBtn = new javax.swing.JButton();
        addImmunizationBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        enrollStudentBtn.setText("Enroll Student");
        enrollStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollStudentBtnActionPerformed(evt);
            }
        });

        registerTeacherBtn.setText("Register Teacher");
        registerTeacherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	registerTeacherBtnActionPerformed(evt);
            }
        });

        welcomeLbl.setBackground(new java.awt.Color(255, 255, 255));
        welcomeLbl.setText("Welcome");

        adminLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        adminLbl.setForeground(new java.awt.Color(255, 0, 0));
        adminLbl.setText("admin");

        title1Lbl.setFont(new java.awt.Font("Bradley Hand", 1, 28)); // NOI18N
        title1Lbl.setText("PRE-SCHOOL");

        title2Lbl.setFont(new java.awt.Font("Marker Felt", 0, 28)); // NOI18N
        title2Lbl.setText("DAY CARE");

        jLayeredPane1.setLayer(title1Lbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(title2Lbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(title1Lbl)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(title2Lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title2Lbl)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        logout.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        logout.setText("Click here to logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        viewStudentsBtn.setText("View All Students");
        viewStudentsBtn.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		viewStudentsBtnActionPerformed(evt);
        	}
        });

        viewTeachersBtn.setText("View All Teachers");
        viewTeachersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTeachersBtnActionPerformed(evt);
            }
        });

        addImmunizationBtn.setText("Add Immunization Records");
        addImmunizationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImmunizationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(welcomeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminLbl))
                    .addComponent(enrollStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerTeacherBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout)
                    .addComponent(viewStudentsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewTeachersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addImmunizationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLbl)
                    .addComponent(adminLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout)
                .addGap(45, 45, 45)
                .addComponent(enrollStudentBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerTeacherBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewStudentsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewTeachersBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addImmunizationBtn)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 380));

        pack();
    }// </editor-fold>                        

    private void enrollStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {    
    	JDialog registerStudentFrame = new Registration();
    	registerStudentFrame.setVisible(true);
        
    }                                        

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {                                    
        System.out.println("Logout clicked");
        JFrame o = new Login();
		o.setVisible(true);
		dispose();
    }   
    
    private void registerTeacherBtnActionPerformed(java.awt.event.ActionEvent evt) {    
    	JDialog registerTeacherFrame = new TeacherRegistrationView();
    	registerTeacherFrame.setVisible(true);
        
    }     
    
    private void viewStudentsBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        JDialog allTeachersView = new AllStudentsView();
        allTeachersView.setVisible(true);
    } 

    private void viewTeachersBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        JDialog allTeachersView = new AllTeachersView();
        allTeachersView.setVisible(true);
    }                                        

    private void addImmunizationBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	JDialog registerStudentFrame = new Immunization();
    	registerStudentFrame.setVisible(true);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton enrollStudentBtn;
    private javax.swing.JButton registerTeacherBtn;
    private javax.swing.JButton viewStudentsBtn;
    private javax.swing.JButton viewTeachersBtn;
    private javax.swing.JButton addImmunizationBtn;
    private javax.swing.JLabel welcomeLbl;
    private javax.swing.JLabel adminLbl;
    private javax.swing.JLabel title1Lbl;
    private javax.swing.JLabel title2Lbl;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logout;
    
//
}
