package edu.neu.csye6200.ui;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;


/**
 *
 * @author pranotidhabu
 */
public class StudentLoginView extends javax.swing.JFrame {

    /**
     * Creates new form StudentLoginView
     */
    public StudentLoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        sidePanel = new JPanel();
        accInfoBtn = new JButton();
        classInfoBtn = new JButton();
        immuneRecBtn = new JButton();
        welcomeLbl = new JLabel();
        studentName = new JLabel();
        deadlinesLbl = new JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        titleLbl1 = new JLabel();
        titleLbl2 = new JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        accInfoPanel = new JPanel();
        studentIDLbl = new JLabel();
        firstNameLbl = new JLabel();
        lastNameLbl = new JLabel();
        dobLbl = new JLabel();
        ageLbl = new JLabel();
        addressLbl = new JLabel();
        studentID = new JLabel();
        firstName = new JLabel();
        lastName = new JLabel();
        dob = new JLabel();
        age = new JLabel();
        address = new JLabel();
        grdFNameLbl = new JLabel();
        grdLNameLbl = new JLabel();
        emailLbl = new JLabel();
        phoneLbl = new JLabel();
        regDateLbl = new JLabel();
        regDate = new JLabel();
        email = new JLabel();
        grdLName = new JLabel();
        phone = new JLabel();
        grdFName = new JLabel();
        grdDetailsLbl = new JLabel();
        classInfoPanel = new JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        classmatesTable = new JTable();
        clsRoomLbl = new JLabel();
        clsRoom = new JLabel();
        teacherLbl = new JLabel();
        teacher = new JLabel();
        clsmatesLbl = new JLabel();
        immuneRecPanel = new JPanel();
        logout = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(600, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(204, 255, 204));

        accInfoBtn.setText("Account info");
        accInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        classInfoBtn.setText("Class info");
        classInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        immuneRecBtn.setText("Immunization records");
        immuneRecBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        //welcomeLbl.setBackground(new java.awt.Color(255, 255, 255));
        welcomeLbl.setText("Welcome");

        studentName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        studentName.setForeground(new java.awt.Color(255, 0, 0));
        studentName.setText("studentName");

        deadlinesLbl.setText("Upcoming deadlines");

        titleLbl1.setFont(new java.awt.Font("Bradley Hand", 1, 28)); // NOI18N
        titleLbl1.setText("PRE-SCHOOL");

        titleLbl2.setFont(new java.awt.Font("Marker Felt", 0, 28)); // NOI18N
        titleLbl2.setText("DAY CARE");

        jLayeredPane1.setLayer(titleLbl1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(titleLbl2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(titleLbl1)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(titleLbl2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleLbl2)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        
        logout.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        logout.setText("Click here to logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(classInfoBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addComponent(accInfoBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                    	.addComponent(immuneRecBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deadlinesLbl)
                            .addComponent(logout)
                            .addGroup(sidePanelLayout.createSequentialGroup()
                                .addComponent(welcomeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentName)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLbl)
                    .addComponent(studentName))
                .addGap(5, 5, 5)
                .addComponent(logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deadlinesLbl)
                .addGap(18, 18, 18)
                .addComponent(accInfoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classInfoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(immuneRecBtn)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 310));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));

        studentIDLbl.setText("StudentID:");

        firstNameLbl.setText("First Name:");

        lastNameLbl.setText("Last Name:");

        dobLbl.setText("Date of Birth:");

        ageLbl.setText("Age:");

        addressLbl.setText("Address:");

        studentID.setText("studentID");

        firstName.setText("firstName");

        lastName.setText("lastName");

        dob.setText("dob");

        age.setText("age");

        address.setText("address");

        grdFNameLbl.setText("Guardian First Name:");

        grdLNameLbl.setText("Guardian Last Name:");

        emailLbl.setText("Email:");

        phoneLbl.setText("Phone:");

        regDateLbl.setText("Registration date:");

        regDate.setText("regDate");

        email.setText("email");

        grdLName.setText("grdLName");

        phone.setText("phone");

        grdFName.setText("grdFName");

        grdDetailsLbl.setText("Guardian details:");

        javax.swing.GroupLayout accInfoPanelLayout = new javax.swing.GroupLayout(accInfoPanel);
        accInfoPanel.setLayout(accInfoPanelLayout);
        accInfoPanelLayout.setHorizontalGroup(
            accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accInfoPanelLayout.createSequentialGroup()
                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dobLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(accInfoPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accInfoPanelLayout.createSequentialGroup()
                                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstName)
                                    .addGroup(accInfoPanelLayout.createSequentialGroup()
                                        .addComponent(studentID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                        .addComponent(regDateLbl))))
                            .addGroup(accInfoPanelLayout.createSequentialGroup()
                                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(phoneLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastName)
                                    .addComponent(address)
                                    .addComponent(dob)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(age)
                                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(accInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(grdLNameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grdLName))
                    .addGroup(accInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(grdFNameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grdFName))
                    .addGroup(accInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(grdDetailsLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regDate)
                .addGap(17, 17, 17))
        );
        accInfoPanelLayout.setVerticalGroup(
            accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentID)
                    .addComponent(regDateLbl)
                    .addComponent(regDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLbl)
                    .addComponent(phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grdDetailsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grdFNameLbl)
                    .addComponent(grdFName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grdLNameLbl)
                    .addComponent(grdLName))
                .addGap(91, 91, 91))
        );

        jTabbedPane1.addTab("Account Info", accInfoPanel);

        classmatesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "First Name", "Last Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(classmatesTable);

        clsRoomLbl.setText("Classroom:");

        clsRoom.setText("clsRoom");

        teacherLbl.setText("Teacher:");

        teacher.setText("teacher");

        clsmatesLbl.setText("Classmates:");

        javax.swing.GroupLayout clsInfoPanelLayout = new javax.swing.GroupLayout(classInfoPanel);
        classInfoPanel.setLayout(clsInfoPanelLayout);
        clsInfoPanelLayout.setHorizontalGroup(
            clsInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clsInfoPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(clsInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clsmatesLbl)
                    .addGroup(clsInfoPanelLayout.createSequentialGroup()
                        .addGroup(clsInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(teacherLbl)
                            .addComponent(clsRoomLbl))
                        .addGap(18, 18, 18)
                        .addGroup(clsInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clsRoom)
                            .addComponent(teacher))))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        clsInfoPanelLayout.setVerticalGroup(
            clsInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clsInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clsInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clsRoomLbl)
                    .addComponent(clsRoom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clsInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherLbl)
                    .addComponent(teacher))
                .addGap(18, 18, 18)
                .addComponent(clsmatesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addGap(111, 111, 111))
        );

        jTabbedPane1.addTab("Class Info", classInfoPanel);

        javax.swing.GroupLayout immuneRecPanelLayout = new javax.swing.GroupLayout(immuneRecPanel);
        immuneRecPanel.setLayout(immuneRecPanelLayout);
        immuneRecPanelLayout.setHorizontalGroup(
            immuneRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );
        immuneRecPanelLayout.setVerticalGroup(
            immuneRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Immunization Records", immuneRecPanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -30, 460, 310));
        jTabbedPane1.getAccessibleContext().setAccessibleName("View info");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);        
    }  

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        
    }    
    
    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {                                    
        System.out.println("Logout clicked");
        JFrame o = new Login();
		o.setVisible(true);
		dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private JButton accInfoBtn;
    private JButton classInfoBtn;
    private JButton immuneRecBtn;
    private JLabel welcomeLbl;
    private JLabel age;
    private JLabel address;
    private JLabel grdFNameLbl;
    private JLabel grdLNameLbl;
    private JLabel emailLbl;
    private JLabel phoneLbl;
    private JLabel regDateLbl;
    private JLabel regDate;
    private JLabel email;
    private JLabel grdLName;
    private JLabel studentName;
    private JLabel phone;
    private JLabel grdFName;
    private JLabel clsRoomLbl;
    private JLabel clsRoom;
    private JLabel teacherLbl;
    private JLabel teacher;
    private JLabel clsmatesLbl;
    private JLabel grdDetailsLbl;
    private JLabel deadlinesLbl;
    private JLabel titleLbl1;
    private JLabel titleLbl2;
    private JLabel studentID;
    private JLabel firstName;
    private JLabel lastName;
    private JLabel dob;
    private javax.swing.JLayeredPane jLayeredPane1;
    private JPanel sidePanel;
    private JPanel immuneRecPanel;
    private JPanel classInfoPanel;
    private JPanel accInfoPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private JTable classmatesTable;
    private JLabel studentIDLbl;
    private JLabel firstNameLbl;
    private JLabel lastNameLbl;
    private JLabel dobLbl;
    private JLabel ageLbl;
    private JLabel addressLbl;
    private JLabel logout;
    // End of variables declaration                   
}
